<?php

/**
 * @file
 * Install file.
 */

/**
 * Implements hook_install().
 */
function domain_install() {
  domain_set_primary_domain();
}

/**
 * Implements hook_schema().
 */
function domain_schema() {
  $schema['domain'] = [
    'description' => 'The base table for domain records',
    'fields' => [
      'domain_id' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Domain numeric id.',
      ],
      'subdomain' => [
        'type' => 'varchar',
        'length' => '255',
        'not null' => TRUE,
        'default' => '',
        'description' => 'Registered DNS entry, will match HTTP_HOST requests',
      ],
      'sitename' => [
        'type' => 'varchar',
        'length' => '255',
        'not null' => TRUE,
        'default' => '',
        'description' => 'Site display name',
      ],
      'scheme' => [
        'type' => 'varchar',
        'length' => '8',
        'not null' => TRUE,
        'default' => 'http',
        'description' => 'Protocol',
      ],
      'valid' => [
        'type' => 'varchar',
        'length' => '1',
        'not null' => TRUE,
        'default' => '1',
        'description' => 'Active status',
      ],
      'weight' => [
        'type' => 'int',
        'unsigned' => FALSE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Sort order',
      ],
      'is_default' => [
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Indicates primary domain',
      ],
      'machine_name' => [
        'type' => 'varchar',
        'length' => '255',
        'not null' => TRUE,
        'default' => '',
        'description' => 'The machine name for this domain.',
      ],
    ],
    'primary key' => ['domain_id'],
    'indexes' => [
      'subdomain' => ['subdomain'],
      'weight' => ['weight'],
      'is_default' => ['is_default'],
    ],
    'foreign_keys' => [
      'domain_id' => ['domain_export' => 'domain_id'],
      'machine_name' => ['domain_export' => 'machine_name'],
    ],
  ];
  $schema['domain_access'] = [
    'description' => 'Stores domain information for each node',
    'fields' => [
      'nid' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Node id, foreign key to {node}',
      ],
      'gid' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Node access grant id',
      ],
      'realm' => [
        'type' => 'varchar',
        'length' => '255',
        'not null' => TRUE,
        'default' => '',
        'description' => 'Node access realm',
      ],
    ],
    'primary key' => ['nid', 'gid', 'realm'],
    'indexes' => [
      'nid' => ['nid'],
    ],
    'foreign_keys' => [
      'nid' => ['node' => 'nid'],
    ],
  ];
  $schema['domain_editor'] = [
    'description' => 'Stores domain information for each user',
    'fields' => [
      'uid' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'User id, foreign key to {user}',
      ],
      'domain_id' => [
        'type' => 'int',
        'unsigned' => FALSE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Domain id, foreign key to {domain}',
      ],
    ],
    'primary key' => ['uid', 'domain_id'],
    'foreign_keys' => [
      'uid' => ['user' => 'uid'],
      'domain_id' => ['domain' => 'domain_id'],
    ],
  ];
  $schema['domain_export'] = [
    'description' => 'Stores canonical machine names for domains.',
    'fields' => [
      'domain_id' => [
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Domain id. Automatic master key.',
      ],
      'machine_name' => [
        'type' => 'varchar',
        'length' => '255',
        'not null' => TRUE,
        'default' => '',
        'description' => 'The machine name for this domain.',
      ],
    ],
    'unique keys' => ['machine_name' => ['machine_name']],
    'indexes' => [
      'domain_id' => ['domain_id'],
    ],
  ];
  return $schema;
}

/**
 * Checks module requirements.
 */
function domain_requirements($phase) {
  $requirements = [];
  switch ($phase) {
    case 'install':
      module_load_include('module', 'domain');
      $root = strtolower(rtrim($_SERVER['HTTP_HOST']));
      if ($error = domain_valid_domain($root)) {
        $requirements['domain'] = [
          'title' => t('Domain Access'),
          'value' => $error . t('If you are using drush, please provide the --uri option (e.g. drush en domain --uri="http://example.com/optional_subdirectory").'),
          'severity' => REQUIREMENT_ERROR,
        ];
      }
      break;
    case 'runtime':
      $messages = [];
      $severity = REQUIREMENT_ERROR;
      // Ensure we have a primary domain.
      $check = domain_default();
      if ($check['domain_id'] == 0) {
        $updated = t('set by an administrator');
        if (user_access('administer domains')) {
          $updated = l(t('set properly'), 'admin/structure/domain');
        }
        $messages[] = t('The site has no primary domain and needs to be !updated.', ['!updated' => $updated]);
      }
      // Check for domain_id 0.
      $list = domain_update_module_check();
      domain_update_messages($messages, $list);

      // Now report.
      $t = get_t();
      if (empty($messages)) {
        $severity = REQUIREMENT_OK;
        $messages[] = t('Module installed correctly.');
      }
      $requirements['domain'] = [
        'title' => $t('Domain Access'),
        'value' => theme('item_list', ['items' => $messages]),
        'severity' => $severity,
      ];
      break;
  }
  return $requirements;
}

/**
 * Implements hook_update_last_removed.
 */
function domain_update_last_removed() {
  return 7311;
}

/**
 * Migrate domain variables to config.
 */
function domain_update_1000() {
  $config = config('domain.settings');
  $config->set('domain_list_size', update_variable_get('domain_list_size', 25));
  $config->set('domain_sitename_override', update_variable_get('domain_sitename_override', 1));
  $config->set('domain_debug', update_variable_get('domain_debug', 0));
  $config->set('domain_force_admin', update_variable_get('domain_force_admin', 0));
  $config->set('domain_vertical_tab', update_variable_get('domain_vertical_tab', 0));
  $config->set('domain_collapse_options', update_variable_get('domain_collapse_options', 0));
  $config->set('domain_www', update_variable_get('domain_www', 0));
  $config->set('domain_search', update_variable_get('domain_search', 0));
  $config->set('domain_seo', update_variable_get('domain_seo', 0));
  $config->set('domain_edit_on_primary', update_variable_get('domain_edit_on_primary', 1));
  $config->set('domain_default_source', update_variable_get('domain_default_source', 0));
  $config->set('domain_default', update_variable_get('domain_default', 0));
  $config->set('domain_grant_all', update_variable_get('domain_grant_all', 'user/*/track'));
  $config->set('domain_cron_rule', update_variable_get('domain_cron_rule', 1));
  $config->set('domain_xmlrpc_rule', update_variable_get('domain_xmlrpc_rule', 0));
  $config->set('domain_paths', update_variable_get('domain_paths', "node/%n node/%n/edit comment/reply/%n node/add/book/parent/%n book/export/html/%n node/%n/outline"));
  $config->set('domain_classes', update_variable_get('domain_classes', 'domain-[current-domain:machine_name]'));
  $config->set('domain_allow_non_ascii', update_variable_get('domain_allow_non_ascii', FALSE));
  $config->set('domain_add_roles', update_variable_get('domain_add_roles', 0));
  $config->set('domain_roles', update_variable_get('domain_roles', []));
  $config->set('domain_mymodule', update_variable_get('domain_mymodule', 0));
  $config->set('domain_behavior', update_variable_get('domain_behavior', 0));
  $config->set('domain_hide_errors', update_variable_get('domain_hide_errors', FALSE));
  $config->set('domain_select_format', update_variable_get('domain_select_format', 0));
  $config->set('domain_scheme', update_variable_get('domain_scheme', 'http://'));
  $config->set('domain_skip_domain_check', update_variable_get('domain_skip_domain_check', 0));
  $config->set('domain_node_', update_variable_get('domain_node_', []));
  $config->set('domain_last_node_update', update_variable_get('domain_last_node_update', 0));
  $config->set('user_picture_default', update_variable_get('user_picture_default', ""));
  $config->set('domain_bootstrap_modules', update_variable_get('domain_bootstrap_modules', []));
  $config->set('anonymous', update_variable_get('anonymous', 'Anonymous'));
  $config->set('settings', update_variable_get('settings', []));
  $config->save();

  update_variable_del('domain_list_size');
  update_variable_del('domain_sitename_override');
  update_variable_del('domain_debug');
  update_variable_del('domain_force_admin');
  update_variable_del('domain_vertical_tab');
  update_variable_del('domain_collapse_options');
  update_variable_del('domain_www');
  update_variable_del('domain_search');
  update_variable_del('domain_seo');
  update_variable_del('domain_edit_on_primary');
  update_variable_del('domain_default_source');
  update_variable_del('domain_grant_all');
  update_variable_del('domain_cron_rule');
  update_variable_del('domain_xmlrpc_rule');
  update_variable_del('domain_paths');
  update_variable_del('domain_classes');
  update_variable_del('domain_allow_non_ascii');
  update_variable_del('domain_add_roles');
  update_variable_del('domain_roles');
  update_variable_del('domain_mymodule');
  update_variable_del('domain_behavior');
  update_variable_del('domain_node_key');
  update_variable_del('domain_hide_errors');
  update_variable_del('domain_select_format');
  update_variable_del('domain_scheme');
  update_variable_del('domain_skip_domain_check');
  update_variable_del('domain_node_type');
  update_variable_del('domain_last_node_update');
  update_variable_del('user_picture_default');
  update_variable_del('domain_bootstrap_modules');
  update_variable_del('anonymous');
  update_variable_del('domain_default');
  update_variable_del('settings');
}
