<?php

/**
 * @file
 * Install file for Domain Conf.
 */

/**
 * Implements hook_schema().
 */
function domain_conf_schema() {
  $schema['domain_conf'] = [
    'description' => 'Stores custom settings for each domain.',
    'fields' => [
      'domain_id' => ['type' => 'int', 'not null' => TRUE, 'default' => 0],
      'settings' => ['type' => 'blob', 'size' => 'big', 'not null' => FALSE],
    ],
    'primary key' => ['domain_id'],
    'foreign_keys' => [
      'domain_id' => ['domain' => 'domain_id'],
    ],
  ];
  return $schema;
}

/**
 * Implements hook_update_last_removed().
 */
function domain_conf_update_last_removed() {
  return 7301;
}
