<?php

/**
 * @file
 * Install file for the Domain Settings module
 */

/**
 * Migrate domain_settings variables to config.
 */
function domain_settings_update_1000() {
  $config = config('domain_settings.settings');
  $config->set('domain_settings_ignore', update_variable_get('domain_settings_ignore', ''));
  $config->set('domain_settings_behavior', update_variable_get('domain_settings_behavior', 0));
  $config->set('domain_settings_form_visibility', update_variable_get('domain_settings_form_visibility', DOMAIN_SETTINGS_SHOW_EXCEPT_LISTED));
  $config->set('domain_settings_forms', update_variable_get('domain_settings_forms', ''));
  $config->set('domain_sitename', update_variable_get('domain_sitename', ''));
  $config->save();

  update_variable_del('domain_settings_ignore');
  update_variable_del('domain_settings_behavior');
  update_variable_del('domain_settings_form_visibility');
  update_variable_del('domain_settings_forms');
}
