<?php

/**
 * @file
 * Install file for the Domain Source module
 */

/**
 * Implements hook_schema().
 */
function domain_source_schema() {
  $schema['domain_source'] = array(
    'description' => 'Stores the canonical domain for each node.',
    'fields' => array(
      'nid' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
      'domain_id' => array('type' => 'int', 'not null' => TRUE, 'default' => 0)),
    'primary key' => array('nid'),
    'foreign_keys' => array(
      'nid' => array('node' => 'nid'),
      'domain_id' => array('domain' => 'domain_id'),
    ),
  );
  return $schema;
}

/**
 * Implements hook_update_last_removed().
 */
function domain_source_update_last_removed() {
  return 7300;
}

/**
 * Migrate domain_source variables to config.
 */
function domain_source_update_1000() {
  $config = config('domain_source.settings');
  $config->set('domain_source_type', update_variable_get('domain_source_type', array()));
  $config->save();
  update_variable_del('domain_source_type');
}
